version: "3.3"
services:

  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  # pgadmin:
  #   image: dpage/pgadmin4
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      # Allow explicit env var override for tests
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: ./backend
      dockerfile: Dockerfile.web
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND?Variable not set}:${TAG-latest}'
    ports:
    - "80:3000"
    build:
      context: ./frontend
      dockerfile: Dockerfile.web
      args:
        FRONTEND_ENV: dev
    
volumes:
  app-db-data:
# Créer le disque dure vietuel