version: "3.3"
services:

  # pgadmin:
  #   ports:
  #     - "5050:5050"

  backend:
    ports:
      - "8888:80"
    volumes:
      - ./backend/app:/app
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
        INSTALL_JUPYTER: ${INSTALL_JUPYTER-true}
    
    command: /start-reload.sh
    
  frontend:
    ports:
    - "80:3000"
    build:
      context: ./frontend
      args:
        FRONTEND_ENV: dev
    volumes:
       - ./frontend/src/:/app/src/
       - ./frontend/package.json:/app/package.json
       - ./frontend/package-lock.json:/app/package-lock.json   
       - ./frontend/node_modules:/app/node_modules
       - ./frontend/.env:/app/.env   
    command: npm start
    
networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
