"""pending quantity and order status

Revision ID: 223d498ca809
Revises: 3cc0c7bbd571
Create Date: 2022-04-13 15:04:05.897171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223d498ca809'
down_revision = '3cc0c7bbd571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('pending_quantity', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('is_done', sa.Boolean(), nullable=True))
    op.drop_index('ix_store_address', table_name='store')
    op.drop_index('ix_warehouse_address', table_name='warehouse')
    op.create_index(op.f('ix_warehouse_address'), 'warehouse', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warehouse_address'), table_name='warehouse')
    op.create_index('ix_warehouse_address', 'warehouse', ['address'], unique=False)
    op.create_index('ix_store_address', 'store', ['address'], unique=False)
    op.drop_column('order', 'is_done')
    op.drop_column('article', 'pending_quantity')
    # ### end Alembic commands ###
