"""order status as enum

Revision ID: 308ca62ddb61
Revises: 223d498ca809
Create Date: 2022-04-13 15:16:12.937404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '308ca62ddb61'
down_revision = '223d498ca809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    orderstatus = postgresql.ENUM('PENDING', 'CANCELLED', 'DONE', name='orderstatus')
    orderstatus.create(op.get_bind())

    op.add_column('order', sa.Column('status', sa.Enum('PENDING', 'CANCELLED', 'DONE', name='orderstatus'), nullable=True))
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.drop_column('order', 'is_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###
