"""empty message

Revision ID: 7c9a88272dd9
Revises: 675d2060e836
Create Date: 2022-04-11 20:26:28.126842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9a88272dd9'
down_revision = '675d2060e836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
