"""Article image

Revision ID: 85f00ba1c86e
Revises: e39432f4996a
Create Date: 2022-04-21 00:53:42.118520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f00ba1c86e'
down_revision = 'e39432f4996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'img')
    # ### end Alembic commands ###
